on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - run: sudo locale-gen de_DE.UTF-8

    - name: generate glossar.html
      run: LC_ALL="de_DE.UTF-8" python generate.py > glossar.html

    - name: publish glossar.html as a release asset
      uses: ncipollo/release-action@v1
      with:
        artifacts: "glossar.html"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "latest"
        allowUpdates: true
